name: Hex Semantic Model Sync
on: # This configures when this workflow will be triggered. This can be further customized to only run when certain files change, etc.
  pull_request: # Run on every pull request
  push: # Run on every push to the main branch.
    branches:
      - main
env:
  TOKEN: ${{ secrets.HEX_SEMANTIC_SYNC_TOKEN }}
  # The top level directory containing your semantic layer files.
  # By default this is your entire repository, but you can update this is you only want to zip a specific subdirectory.
  DIRECTORY: metricflow
jobs:
  hex-semantic-model-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Zip repository
      run: |
          cd $DIRECTORY
          zip -r repo.zip .
    - name: Semantic model sync
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
          response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
            -F "data=@$DIRECTORY/repo.zip" \
            https://rc.hex.tech/api/v1/semantic-models/7c4ecde7-dfee-4a5b-9e6b-898d832a3178/sync \
            -H "Authorization: Bearer $TOKEN")
          if [ "$response" -eq 201 ]; then
            echo "✅ Successfully uploaded semantic layer."
            cat response.txt | jq 'del(.debug)'
          else
            echo "❌ Failed to upload semantic layer."
            cat response.txt
            exit 1
          fi
    - name: Semantic model sync (dry run)
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      run: |
          response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
            -F "data=@$DIRECTORY/repo.zip" \
            -F "dryRun=true" \
            https://rc.hex.tech/api/v1/semantic-models/7c4ecde7-dfee-4a5b-9e6b-898d832a3178/sync \
            -H "Authorization: Bearer $TOKEN")
          if [ "$response" -eq 201 ]; then
            echo "✅ Successfully validated semantic layer."
            cat response.txt | jq 'del(.debug)'
          else
            echo "❌ Validation failed for semantic layer."
            cat response.txt
            exit 1
          fi
